[17.705678940] 2018-12-28 18:14:48,705 - INFO - launcher: Starting sanity checks
[17.977714539] 2018-12-28 18:14:48,705 - INFO - launcher: Checking for python 3.5+
[18.154144287] 2018-12-28 18:14:48,705 - INFO - launcher: Checking console encoding
[18.317461014] 2018-12-28 18:14:48,706 - INFO - launcher: Ensuring we're in the right folder
[18.759965897] 2018-12-28 18:14:48,706 - INFO - launcher: Checks passed.
[18.935918808] 2018-12-28 18:14:48,706 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[1.419635057] launcher-ERROR: Error starting bot
Traceback (most recent call last):
  File "runJ.py", line 344, in main
    m = MusicBot('../jMusicBot/config/options.ini', '../jMusicBot/config/permissions.ini')
  File "/home/ubuntu/MusicBot/musicbot/bot.py", line 74, in __init__
    self.config = Config(config_file)
  File "/home/ubuntu/MusicBot/musicbot/config.py", line 16, in __init__
    self.find_config()
  File "/home/ubuntu/MusicBot/musicbot/config.py", line 217, in find_config
    shutil.copy('../MusicBot/config/example_options.ini', self.config_file)
  File "/usr/lib/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '../jMusicBot/config/options.ini'
[1.425860643] launcher-INFO: All done.
